- name: Install gogs in ubuntu machines
  hosts: all
  tasks:
    - name: Install git
      apt: name=git update_cache=yes state=latest

    - name: Download gogs
      get_url: url=https://dl.gogs.io/0.11.29/linux_amd64.tar.gz dest=/opt/linux_amd64.tar.gz

    - name: Extract archive
      command: chdir=/usr/share /bin/tar xvf /opt/linux_amd64.tar.gz -C /opt/ creates=/opt/gogs
