---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:

    - name: Install git
      apt: name=git update_cache=yes state=latest

    - name: Download gogs
      get_url: url=https://dl.gogs.io/0.11.29/linux_amd64.tar.gz dest=/opt/linux_amd64.tar.gz

    - name: Extract archive
      command: chdir=/usr/share /bin/tar xvf /opt/linux_amd64.tar.gz -C /opt/ creates=/opt/gogs

    - name: Finished Installation
      command: echo 'Gogs installed and runnig \n'
